### ISSUE TITLE
闪光灯报错

### ISSUE THREAD

**Issue by guangmingxiong9999** [ailiwean/NBZxing#10]
在扫码完成的的瞬间开启关闭闪光灯，报错找不到相机  

Process: com.xkb.education, PID: 31309
    java.lang.IllegalStateException: Session has been closed; further changes are illegal.
        at android.hardware.camera2.impl.CameraCaptureSessionImpl.checkNotClosed(CameraCaptureSessionImpl.java:672)
        at android.hardware.camera2.impl.CameraCaptureSessionImpl.setRepeatingRequest(CameraCaptureSessionImpl.java:235)
        at com.google.android.cameraview.Camera2.setFlash(Camera2.java:327)
        at com.google.android.cameraview.Camera2.lightOperator(Camera2.java:380)
        at com.google.android.cameraview.BaseCameraView.lightOperator(BaseCameraView.kt:226)
        at com.xkb.education.ui.mine.scanner.MineScannerActivity4.onViewClicked(MineScannerActivity4.java:370)
        at

**Comment by ailiwean** [comment]
嗯，  异步操作崩溃了，   今下班后改一下

**Comment by ailiwean** [comment]
已修复
