### ISSUE TITLE
扫码崩溃

### ISSUE THREAD

**Issue by liyeyu** [ailiwean/NBZxing#2]
java.lang.IllegalStateException
        at android.media.MediaPlayer.prepareAsync(Native Method)
        at com.wishzixing.lib.util.RxBeepUtils.playBeep(RxBeepUtils.java:30)
        at com.wishzixing.lib.able.DecodePixAble.cusAction(DecodePixAble.java:40)
        at com.wishzixing.lib.manager.PixsValuesCusManager$1.run(PixsValuesCusManager.java:56)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:764)

**Comment by ailiwean** [comment]
收到，  谢谢反馈， 近期内处理

**Comment by ailiwean** [comment]
以处理

**Comment by ailiwean** [comment]
已处理
