### ISSUE TITLE
androidx 打开崩溃

### ISSUE THREAD

**Issue by weixuefeng** [ailiwean/NBZxing#6]
```
java.lang.RuntimeException: Unable to start activity ComponentInfo{org.developer.fcmtest/org.developer.fcmtest.view.ScanActivity}: android.view.InflateException: Binary XML file line #6: Binary XML file line #6: Error inflating class org.developer.fcmtest.widget.CusZxingView
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3430)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3614)
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:86)
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2199)
        at android.os.Handler.dispatchMessage(Handler.java:112)
        at android.os.Looper.loop(Looper.java:216)
        at android.app.ActivityThread.main(ActivityThread.java:7625)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:524)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:987)
     Caused by: android.view.InflateException: Binary XML file line #6: Binary XML file line #6: Error inflating class org.developer.fcmtest.widget.CusZxingView
     Caused by: android.view.InflateException: Binary XML file line #6: Error inflating class org.developer.fcmtest.widget.CusZxingView
     Caused by: java.lang.reflect.InvocationTargetException
        at java.lang.reflect.Constructor.newInstance0(Native Method)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:343)
        at android.view.LayoutInflater.createView(LayoutInflater.java:658)
        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:801)
        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:741)
        at android.view.LayoutInflater.rInflate(LayoutInflater.java:874)
        at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:835)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:515)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:423)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:374)
        at androidx.appcompat.app.AppCompatDelegateImpl.setContentView(AppCompatDelegateImpl.java:555)
        at androidx.appcompat.app.AppCompatActivity.setContentView(AppCompatActivity.java:161)
        at org.developer.fcmtest.view.ScanActivity.onCreate(ScanActivity.kt:18)
        at android.app.Activity.performCreate(Activity.java:7458)
        at android.app.Activity.performCreate(Activity.java:7448)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1286)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3409)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3614)
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:86)
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2199)
        at android.os.Handler.dispatchMessage(Handler.java:112)
        at android.os.Looper.loop(Looper.java:216)
        at android.app.ActivityThread.main(ActivityThread.java:7625)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:524)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:987)
     Caused by: java.lang.BootstrapMethodError: Exception from call site #3 bootstrap method
        at com.google.android.cameraview.CameraView.setAspectRatio(CameraView.java:418)
        at com.google.android.cameraview.CameraView.<init>(CameraView.java:142)
        at com.google.android.cameraview.BaseCameraView.<init>(BaseCameraView.kt:30)
        at com.ailiwean.core.view.ZxingCameraView.<init>(ZxingCameraView.kt:34)
2020-07-17 21:49:35.939 11097-11097/org.developer.fcmtest E/AndroidRuntime:     at org.developer.fcmtest.widget.CusZxingView.<init>(CusZxingView.kt:17)
        at org.developer.fcmtest.widget.CusZxingView.<init>(CusZxingView.kt:17)
        at org.developer.fcmtest.widget.CusZxingView.<init>(Unknown Source:6)
        	... 28 more
     Caused by: java.lang.ClassCastException: Bootstrap method returned null
        	... 35 more
```

**Comment by ailiwean** [comment]
大哥，你用法不对吧， 我估计你的kotlin没加@JvmOverloads
